### ISSUE TITLE
Do we need EPUB & PDF builds?

### ISSUE THREAD

**Issue by ghost** [org-id/handbook#23]
I think we normally turn these off.

Also it's giving a crash when doing #17 & #20 - something in the `jsonschema` directive

**Comment by kd-ods** [comment]
I don't know that anyone is making use of these pdf and epub versions. I can't imagine they are.

Let's turn them off. If it turns out that that does step on anyone's toes, we can look at a proper fix. Does that sound ok?

**Comment by ghost** [comment]
Ok, turning these off
